language: rust
rust:
  - 1.35.0
  - stable
  - nightly
script:
  - cargo build --no-default-features --verbose --all
  - cargo build --verbose --all
  - cargo test --verbose --all
  - if [ $TRAVIS_RUST_VERSION == "nightly" ]; then
        env RUSTFLAGS="-Z sanitizer=address" cargo +nightly test --test tests --target x86_64-unknown-linux-gnu;
    fi
