[package]
name = "ttf-parser"
version = "0.2.1"
authors = ["Evgeniy Reizner <razrfalcon@gmail.com>"]
keywords = ["ttf", "truetype", "opentype"]
categories = ["parser-implementations"]
license = "MIT/Apache-2.0"
description = "A high-level, safe, zero-allocation TrueType font parser."
repository = "https://github.com/RazrFalcon/ttf-parser"
documentation = "https://docs.rs/ttf-parser/"
readme = "README.md"
edition = "2018"
exclude = ["fonts/**"]

[dev-dependencies]
bencher = "0.1"
svgtypes = "0.5.0"
time = "0.1"
xmlwriter = "0.1.0"

[[bench]]
name = "outline"
harness = false

[[bench]]
name = "methods_perf"
harness = false

[[bench]]
name = "methods_perf_x1000"
harness = false
